language: generic 
sudo: required
  services:
    - docker

before_install:
  - docker build -t parmatt61/docker-react -f Dockerfile.dev .



script:
  - docker run parmatt61/docker-react npm run test -- --coverage